// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Test;
//
//    var login = Login.FromJson(jsonString);

namespace Test
{
    using System.Collections.Generic;

    using Newtonsoft.Json;

    public partial class LoginDTO
    {
        [JsonProperty("CMD")]
        public int Cmd { get; set; }

        [JsonProperty("UID")]
        public string Uid { get; set; }

        [JsonProperty("QRY")]
        public string Qry { get; set; }

        [JsonProperty("EXE")]
        public int Exe { get; set; }

        [JsonProperty("HNDL")]
        public int Hndl { get; set; }

        [JsonProperty("VER")]
        public string Ver { get; set; }

        [JsonProperty("MOD")]
        public int Mod { get; set; }

        [JsonProperty("ADMIN")]
        public int Admin { get; set; }

        [JsonProperty("COUNTER")]
        public int Counter { get; set; }

        [JsonProperty("BROADCAST")]
        public int Broadcast { get; set; }

        [JsonProperty("LANGUAGE")]
        public int Language { get; set; }

        [JsonProperty("CLIENT")]
        public int Client { get; set; }
    }
}
